"
This is a base class for a visitor that has to resolve FFIExternalTypes.
"
Class {
	#name : #FFIExternalTypeVisitor,
	#superclass : #Object,
	#category : #'Lowcode-FFI-Types'
}

{ #category : #visitor }
FFIExternalTypeVisitor >> visitBoolType: type [
]

{ #category : #'as yet unclassified' }
FFIExternalTypeVisitor >> visitCharacterType: type [
]

{ #category : #'as yet unclassified' }
FFIExternalTypeVisitor >> visitExternalAddressType: type [
]

{ #category : #'as yet unclassified' }
FFIExternalTypeVisitor >> visitExternalObjectType: type [
]

{ #category : #'as yet unclassified' }
FFIExternalTypeVisitor >> visitExternalStructureType: type [
]

{ #category : #'as yet unclassified' }
FFIExternalTypeVisitor >> visitExternalUnionType: type [
]

{ #category : #visitor }
FFIExternalTypeVisitor >> visitFloat32Type: type [
]

{ #category : #visitor }
FFIExternalTypeVisitor >> visitFloat64Type: type [
]

{ #category : #visitor }
FFIExternalTypeVisitor >> visitInt16Type: type [
]

{ #category : #visitor }
FFIExternalTypeVisitor >> visitInt32Type: type [
]

{ #category : #visitor }
FFIExternalTypeVisitor >> visitInt64Type: type [
]

{ #category : #visitor }
FFIExternalTypeVisitor >> visitInt8Type: type [
]

{ #category : #visitor }
FFIExternalTypeVisitor >> visitUInt16Type: type [
]

{ #category : #visitor }
FFIExternalTypeVisitor >> visitUInt32Type: type [
]

{ #category : #visitor }
FFIExternalTypeVisitor >> visitUInt64Type: type [
]

{ #category : #visitor }
FFIExternalTypeVisitor >> visitUInt8Type: type [
]

{ #category : #visitor }
FFIExternalTypeVisitor >> visitVoidType: type [
]
